//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrcunBlog.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Blog
    {
        public int BlogID { get; set; }
        public string BlogBaslik { get; set; }

        [UIHint("tinymce_full")] [AllowHtml]
        public string BlogIcerik { get; set; }
        public string Foto { get; set; }
        public Nullable<int> BlogOkunmaSayisi { get; set; }
        public Nullable<int> BlogOkunmaSuresi { get; set; }
        public Nullable<System.DateTime> BlogTarih { get; set; }
    }
}
